config/routes.rb
Rails.application.routes.draw do
  root to: "songs#index"
  devise_for :users
  resources :songs do
    resources :words
  end
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/song.rb
class Song < ApplicationRecord
  has_many :words, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :songs
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :song
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = current_user.songs.build
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = current_user.songs.build(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:title, :artist, :album, :description, :lyrics, :englyrics)
    end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  
  def index
  end
  
  def create
    @song = Song.find(params[:song_id])
    @word = @song.words.create(word_params)
    redirect_to song_path(@song)
  end

  def destroy
    @song = Song.find(params[:song_id])
    @word = @song.words.find(params[:id])
    @word.destroy
    redirect_to song_path(@song)
  end
  private
  def word_params
    params.require(:word).permit(:mot, :meaning, :origin, :word_speech, :example)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Songwordfirst</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='//fonts.googleapis.com/css?family=Libre+Baskerville|Work+Sans' 
rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Poller+One' 
rel='stylesheet' type='text/css'> 
  </head>
  <body>
  
    <% if notice %>
    <div id="notice_wrapper">
      <p class="notice"><%= notice %></p>
    </div>  
    <% elsif alert %>
    <div id="notice_wrapper">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>
  
    <nav class="navbar navbar-custom">
    <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Song Word', root_path, :class => "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to 'New Song', new_song_path %></li>   
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account<span class="caret"></span></a>
          <ul class="dropdown-menu">
          <% if user_signed_in? %>
            <li><%= link_to 'Account', edit_user_registration_path %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <li><%= link_to 'Sign In', new_user_session_path %></li>
          <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
    </div>
    </nav>

  <div class="container-fluid">
    <%= yield %>
  </div>  
  </body>
</html>

app/views/songs/_form.html.erb
<%= form_with(model: song, local: true) do |form| %>
  <% if song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :song_title, :class => 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :artist %>
    <%= form.text_field :artist, id: :song_artist, :class => 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :album %>
    <%= form.text_field :album, id: :song_album, :class => 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :description %>
    <%= form.text_area :description, id: :song_description, :class => 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :lyrics %>
    <%= form.text_area :lyrics, id: :song_lyrics, :size => '30x10', :class => 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label 'English Lyrics' %>
    <%= form.text_area :englyrics, id: :song_englyrics, :size => '30x10', :class => 'form-control' %>
  </div>

  <div class="actions form-group">
    <%= form.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<div class="row">
<h1 class="page-header text-center">Editing Song</h1>
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form', song: @song %>
    <br><br>
    <%= link_to 'Show', @song, :class => "btn btn-success btn-sm" %> 
    <%= link_to 'Back', songs_path, :class => "btn btn-primary btn-sm" %>
    <br><br>
  </div>
</div>

app/views/songs/index.html.erb
<h1 class="page-header page-title text-center">Songs</h1>
  <% @songs.each_slice(3) do |songs| %>
  <div class="row">
      <% songs.each do |song| %>
      <div class="col-md-4 song-box">
        <div class="panel panel-default"> 
          <div class="panel-heading">
            <h2 class="panel-title page-header"><span class="glyphicon glyphicon-music" aria-hidden="true"></span> <%= song.title %></h2>
            <div class="well well-sm"> 
                   <span class="glyphicon glyphicon-user" aria-hidden="true"></span> Artist
                   <span class="label label-success"> <%= song.artist %></span>
                   &nbsp;&nbsp;&nbsp;&nbsp;
                   <span class="glyphicon glyphicon-sound-stereo" aria-hidden="true"></span> Album
                   <span class="label label-primary"><%= song.album %></span>     
            </div>
          </div>
          
          <div class ="panel-body">    
            
            <h4><q><%= truncate(song.lyrics) %></q></h4>
            <p><%= truncate(song.englyrics) %></p>
              
            <div class="btn-group btn-group-justified">
              <%= link_to 'View Lyrics', song, :class => 'btn btn-primary btn-sm' %>
              <% if song.user == current_user %>
                  <%= link_to 'Edit Lyrics', edit_song_path(song), :class => 'btn btn-warning btn-sm' %>
                  <%= link_to 'Delete Lyrics', song, :class => 'btn btn-danger btn-sm', method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            </div> <!-- btn-group-justified -->
          
          </div> <!--panel-body-->
        
        </div> <!--Panel-default-->
      </div> <!--Col-md-4-->
      <% end %>
    </div>
  <% end %>   

app/views/songs/new.html.erb
<div class="row">
  <h1 class="page-header text-center">New Song</h1>
    <div class="col-md-6 col-md-offset-3">
      <%= render 'form', song: @song %>
      <br>
      <%= link_to 'Back', songs_path, :class => "btn btn-primary btn-sm" %>
      <br><br><br>
    </div>
</div>

app/views/songs/show.html.erb
<div class="row text-center">
  <p>
    <h1 class="page-header"><%= @song.title %></h1>
  </p>

  <h4>
    <b>Artist </b>
      <span class="label label-success"><%= @song.artist %></span>
    <b>Album</b> 
      <span class="label label-primary"><%= @song.album %></span>
    <b>Added By</b> 
      <span class="label label-primary"><%= @song.user.email %></span>  
  </h4>

  <p class="lead">
    <strong>Description -</strong>
    <%= @song.description %>
  </p>
  <div class="col-md-4">
    <p>
      <h2><strong>Lyrics</strong></h2>
      <%= simple_format(@song.lyrics) %>
    </p>
  </div>
  <div class="col-md-4">
    <p>
      <h2><strong>English lyrics</strong></h2>
      <%= simple_format(@song.englyrics) %>
    </p> 
  </div>
 <div class="col-md-4 text-justify">
    <h2>Words </h2>
    <%= render 'words/words'%>
    <% if @song.user == current_user %> 
  <h2>Add a Word: </h2>
    <%= render 'words/form' %>
    <% end %>
 </div>
 <div class="col-md-12 text-justify">
  <br><br>
    <% if @song.user == current_user %> 
    <div class="btn-group pull-left">
    <%= link_to 'Edit Lyrics', edit_song_path(@song), :class => 'btn btn-warning btn-sm' %>
    <%= link_to 'Delete Lyrics', @song, :class => 'btn btn-danger btn-sm', method: :delete, data: { confirm: 'Are you sure?' } %>
    </div> 
    <% end %>
    <%= link_to 'Back', songs_path, :class => 'btn btn-primary pull-right btn-sm' %>
    <div class="clearfix"></div>
  <br><br> 
  </div>
</div>

app/views/words/_form.html.erb
<%= form_for([@song, @song.words.build], :html => {:class => "form-horizontal"} ) do |f| %>
   <div class="field form-group">
    <%= f.label 'Word', :class => 'col-md-4' %>
    <div class="col-md-8">
    <%= f.text_field :mot, id: :mot_title, :class => 'form-control' %>
    </div>
   </div>
   <div class="field form-group">
    <%= f.label :meaning, :class => 'col-md-4' %>
    <div class="col-md-8">
    <%= f.text_area :meaning, id: :mot_meaning, :class => 'form-control' %>
    </div>
   </div>
   <div class="field form-group">
    <%= f.label :origin, :class => 'col-md-4' %>
    <div class="col-md-8">
    <%= f.text_area :origin, id: :mot_origin, :class => 'form-control' %>
   </div>
   </div>
   <div class="field form-group">
    <%= f.label :word_speech, :class => 'col-md-4' %>
    <div class="col-md-8">
    <%= f.text_area :word_speech, id: :mot_type, :class => 'form-control' %>
   </div>
   </div>
   <div class="field form-group">
    <%= f.label :example, :class => 'col-md-4' %>
    <div class="col-md-8">
    <%= f.text_area :example, id: :mot_example, :class => 'form-control' %>
   </div>
   </div>
   <div class="field form-group text-center">
   <br>
    <%= f.submit :class => 'btn btn-primary' %>
   </div>
<% end %>

app/views/words/_words.html.erb
<% @song.words.each do |word| %>
 <div class="panel panel-default">
 <div class="panel-heading">   
    <h2 class="panel-title"><%= word.mot %></h2>
 </div>
 <div class="panel-body word-body-panel">  
 <table class="table table-condensed word-table">
  <tr>
    <th>Meaning: </th>
    <td><%= word.meaning %></td> 
  </tr>
  <tr>
    <th>Origin:</th>
    <td><%= word.origin %></td> 
  </tr>
  <tr>
    <th>Speech:</th>
    <td><%= word.word_speech %></td> 
  </tr>
  <tr>
    <th>Example:</th>
    <td><%= word.example %></td> 
  </tr>
  <% if @song.user == current_user %> 
  <tr>
    <td class="word-delete" colspan="2"><%= link_to "Remove", [word.song, word], method: :delete, data: { confirm: 'Are you sure super stupid?'}, :class => "btn btn-danger btn-sm" %><td>
  </tr>
  <% end %>
  </table>
</div>
</div>  
<% end %>

app/views/words/index.html.erb
<h1>Hello, World</h1>